### ISSUE TITLE
Tests Structure Request

### ISSUE THREAD

**Issue by icruzr93** [javieraviles/node-typescript-koa-rest#26]
Hi, this is an amazing boilerplate project and i'd like to say thanks for this; i'd like to suggest a basic implementation to make use of a testing library. It could be great with that.

**Comment by javieraviles** [comment]
First of all thank you! I'm glad you could find it useful.

Mmmm... I would probably go with Mocha and Chai, as for another Electron app that I have on production I got some experience there already... will try to grab some time and add it. For today I have updated a couple of libraries here.

On the other hand, if somebody feels like doing it, a PR would be more than welcome 😃

**Comment by rafapaezbas** [comment]
Hi,

what do you think of Jest? https://jestjs.io/

It can support Typescript and Ii looks simple and easy to include. https://www.nerd.vision/post/testing-a-typescript-project-with-jest-ts-jest

**Comment by javieraviles** [comment]
Hey it looks dope! I just saw you also opened a PR already so I am having a look ASAP, thanks!!!

**Comment by javieraviles** [comment]
Covered by #73 thanks!!
