### ISSUE TITLE
Default build fails because src/public does not exist

### ISSUE THREAD

**Issue by am-a** [javieraviles/node-typescript-koa-rest#29]
Not sure if there are assets missing from the repo or if this copying is supposed to be optional. I can open a PR if I know which

**Comment by javieraviles** [comment]
Mmm are you sure the build is failing? Maybe is throwing the _"cp: no such file or directory..."_, as part of the **"npm run build"** command is copying assets from an optional **"src/public/**/*"** directory. But this should not stop you from building.

For the  **"npm run watch-server"** command, no assets copy is needed, as it runs directly in Typescript; the thing is when compiling the JS to create a "build" directory, if you are using some assets, they should be copied over to the folder, wherever they are. As an example, I created the file called `copyStaticAssets.ts`, where the paths of the assets to be copied can be specified. Just for the sake of having something on it, I included 3 typical paths where people include assets, but I didn't store anything there...
