### ISSUE TITLE
Run migrations

### ISSUE THREAD

**Issue by helderjnpinto** [javieraviles/node-typescript-koa-rest#33]
hi, thanks for the boilerplate, 
how i can create the database for this?

**Comment by javieraviles** [comment]
If you have the project already running with PostgreSQL (only needed to `docker-compose up` the boilerplate and everything should be fine), in the [server.ts](https://github.com/javieraviles/node-typescript-koa-rest/blob/master/src/server.ts) file you will find the TypeORM connection. There you can specify the migrations directory and table (if you don't specify anything, it has already some default values); you can find very straightforward documentation about config migrations in TypeORM [here](https://github.com/typeorm/typeorm/blob/master/docs/migrations.md).

I'm not sure whether I am answering your question or not... You don't need to do anything in the DB itself, so I guess this is what you wanted to know :)

I'm glad you enjoy the project

**Comment by helderjnpinto** [comment]
thx, when i run this command: 
typeorm migration:run 

i have this error: 
`api/src/entity/user.ts:1
(function (exports, require, module, __filename, __dirname) { import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
`

**Comment by helderjnpinto** [comment]
yes, npm run build solve the problem, thanks!
