### ISSUE TITLE
Loading the configuration file

### ISSUE THREAD

**Issue by petrodstrcil** [javieraviles/node-typescript-koa-rest#36]
I noticed that in the server.ts file is the configuration read after import.

```
import * as dotenv from 'dotenv';
import { config } from './config';
// Load environment variables from .env file, where API keys and passwords are configured
dotenv.config({ path: '.env' });
```

Shouldn't it be the opposite?

```
import * as dotenv from 'dotenv';
// Load environment variables from .env file, where API keys and passwords are configured
dotenv.config({ path: '.env' });
import { config } from './config';
```

**Comment by javieraviles** [comment]
to be honest with you i don't think `dotenv.config({ path: '.env' });` is even needed in server.ts, as only `config.ts` should be the one reading env variables. Then any file can import `config.ts` and use it, without worrying where those variables come from... I think in `server.ts` only line `import { config } from './config';` should remain.

This is probably some leftovers from some initial stages when I had no `config.ts`... Thanks for reporting.

Regards,
Javi

**Comment by javieraviles** [comment]
removed the leftovers here https://github.com/javieraviles/node-typescript-koa-rest/pull/40 thanks!
