### ISSUE TITLE
How to initialize the database?

### ISSUE THREAD

**Issue by gaoshijun1993** [javieraviles/node-typescript-koa-rest#37]
When GET /users,  throw error ``` RepositoryNotFoundError: No repository for "User" was found. Looks like this entity is not registered in current "default" connection?```

**Comment by javieraviles** [comment]
In `server.ts` file you register your entities; 

    ` entities: [
       'dist/entity/**/*.js'
    ],`

There it is specified, your entities are javascript files in such directory. They will appear there when you perform `npm run build`. If you want to run typescript directly with `npm run watch-server` is fine, but then you will need to change the entities dir to the typescript files.

Let me know whether it helped :)

Regards,
Javi

**Comment by gaoshijun1993** [comment]
Thank you for your instant reply, and it worked, it would be much better if there is a universal setting for it😥😥😥
