### ISSUE TITLE
Winston cannot write log to log file

### ISSUE THREAD

**Issue by gaoshijun1993** [javieraviles/node-typescript-koa-rest#38]
The log filename has to be absolute path like: path.resolve(__dirname, 'error.log'), which issue can be found here: https://github.com/winstonjs/winston/issues/1001

**Comment by javieraviles** [comment]
would you mind creating a pull request, please?

thanks in advance :)

**Comment by javieraviles** [comment]
I just gave it a try and it works perfectly fine for me as it is right now... it creates the error.log file and contains the logs... am I maybe missing something?

**Comment by javieraviles** [comment]
Just fixed this using your path solution, here the PR, will merge it probably tomorrow, thanks!

https://github.com/javieraviles/node-typescript-koa-rest/pull/59
