### ISSUE TITLE
watch-server doesn't work on windows 10

### ISSUE THREAD

**Issue by ElsaOOo** [javieraviles/node-typescript-koa-rest#39]
in my addition, nodemon can't monitor src folder code change.
unless i edit the script code 
` "watch-server": "nodemon --watch src -e ts,tsx --exec ts-node src/server.ts",`

this works!

**Comment by javieraviles** [comment]
I just did a quick test and you are right... could you please address a pull request for this? it would be nice :)

thanks in advance

**Comment by javieraviles** [comment]
I fixed it here https://github.com/javieraviles/node-typescript-koa-rest/pull/40

thanks!
