### ISSUE TITLE
Feedback: This project kicks ass.

### ISSUE THREAD

**Issue by JamesG-DPharos** [javieraviles/node-typescript-koa-rest#42]
Hey @javieraviles

I just wanted to say thanks for this. Of all the "generators / templates" out there that I have used this is by far the best. Very lightweight and has excellent functionality - a perfect starter kit.

The only thing I had trouble with was winston as #38 . Whenever you are throwing an error it never gets to log (regardless if you set the file path). I switched it out with koa-bunyan-logger and it's far more usable.

The one and **ONLY** thing I would consider adding to the main repo is AJV for validating the request https://www.npmjs.com/package/ajv . I didn't need AJV for this particular project but I will look into sending a future PR with AJV validation in TypeScript (if you are interested).

Other than that, I hope you keep it lightweight.

Anyone looking at this a potential starter for your next rest project, I highly recommend it.

Anyways, thanks!

**Comment by javieraviles** [comment]
Hi! thanks for the feedback :)

There is a dependency named "class-validator" in the project which will already cover entities validation... where would you see the use-case to add AJV? I didn't know the project but looks very good...

Could you comment on issue #38 how to reproduce the error so I can fix it please? that would help!

Regards,
Javi

**Comment by JamesG-DPharos** [comment]
Yeah, I can see your point about the Class Validators - I didn't consider that to be the same thing originally but it really is. So yeah, so forget that, not need for AJV; my apologies.

Let me roll back and give you some real info about the winston logger, probably tomorrow, but I can say for sure that a KOA throw will not log an error mid stream. `ctx.throw(401, 'Unauthorized');`

**Comment by vbgrigorjev** [comment]
Can anyone help me? I've just installed this project, and when I start it, I have an " TypeORM connection error:  error: password authentication failed for user "user" ". I am very new to backend development, from where username of db comes from?

**Comment by javieraviles** [comment]
Based on the [Error Handling](https://github.com/koajs/koa/wiki/Error-Handling) section from the KOA wiki, is recommended to introduce as one of the first middlewares; this way the logger class would be a perfect suit for it:
        `try {
            await next();
        } catch (err) {
            ctx.status = err.status || 500;
            ctx.body = err.message;
        }` 

It will therefore log also throws and any other unexpected error.

**Comment by javieraviles** [comment]
Just implemented it here

https://github.com/javieraviles/node-typescript-koa-rest/pull/59

works great, will probably merge it tomorrow, thanks!
