### ISSUE TITLE
watch启动报错，类型不匹配啊

### ISSUE THREAD

**Issue by wowtrxqn** [javieraviles/node-typescript-koa-rest#56]
![1ADAB533-D2E9-41C5-AE5C-D612132CCE48](https://user-images.githubusercontent.com/24369118/73634059-45043400-469b-11ea-83b2-f16caae96fb2.png)

**Comment by wuxjim** [comment]
no-modules->pg-connection-string->index.ts->coparse 第 7 行，改 string 为 number.

估计是库版本问题吧，　port 的类型定义不一样，在 ConnectionOptions 里是 number.....

**Comment by javieraviles** [comment]
Since I am now passing the entire url directly:

`createConnection({
    type: "postgres",
    url: config.databaseUrl,
    synchronize: true,
    logging: false,
    entities: config.dbEntitiesPath,
    extra: {
        ssl: config.dbsslconn, // if not development, will use SSL
    }
})`

This will not be an issue anymore :)

Thanks!
