### ISSUE TITLE
Need more infor on jwt.io

### ISSUE THREAD

**Issue by pgdesigning** [javieraviles/node-typescript-koa-rest#60]
This is an awesome project. Thank you so much for getting this out. 

I find it very helpful and I started using it for a personal project that I'm heavily involved with the API related work.

I noticed that this should have more helpful information when using the jwt.io when generating the token for integration testing and API testing. 

I can create a PR if you are ok with that. Please let me know.

**Comment by javieraviles** [comment]
Great to see you find it helpful!

So you mean extend the documentation when it comes to "how i get my jwt" for example? sure open a PR with your suggestions and let's discuss it here. Every feedback and improvement from community is more than welcome.

**Comment by javieraviles** [comment]
closing this issue as does not seem to be any further details on what would be nice to improve in the docs
