### ISSUE TITLE
start npm run watch-server error (fresh install)

### ISSUE THREAD

**Issue by Paul75** [javieraviles/node-typescript-koa-rest#63]
Hello,

I clone, install and run npm run watch-server got this error : 

```
var eventName = msg.name === 'error' ? 'errorMessage' : msg.name
                          ^
TypeError: Cannot read property 'name' of undefined
```

Thanks

**Comment by javieraviles** [comment]
Hi Paul,

I believe there is an issue with your connection to Postgres. Unfortunately, node-postgres library error message y very poor in this case, see https://github.com/brianc/node-postgres/issues/1940

Do you have a running local/docker Postgres? if so, check the connection parameters. IF anything I'm around :)

**Comment by Paul75** [comment]
Hello 

Sorry but use MySQL for database.

**Comment by javieraviles** [comment]
I see that is then definitely the issue. If you want to use MySQL, you will then have to bring to your node project some mysql drivers so you can connect to it

**Comment by Paul75** [comment]
I installalled module MySQL and same....

**Comment by javieraviles** [comment]
what dependency did you install?
how are you now connecting to mysql?

**Comment by Paul75** [comment]
Npm i --save npm
Not works

**Comment by javieraviles** [comment]
sorry this issue i not related with this project anymore so I will just close it. If you feel like you need some help learning node there are plenty of resources out there., good luck!

**Comment by Paul75** [comment]
Okay seems not want to help !

Great answer ! It IS n'ont problem of node but yours project !

Another project works fine !

Bad answer ....

**Comment by javieraviles** [comment]
1) `Npm i --save npm` that **is not the command you used**. So the minimum to receive help is providing valid information.
2) **my project works perfectly fine with postgres**, if you want to use mysql, you will need a real dependency for mysql drivers and read [ typeorm documentation](https://typeorm.io/#/) to know how to connect to mysql, it is very easy, but you have to at least show the code that did not work for you to again receive help. This is how TypeORM tells you to connect to MySQL:

```
createConnection({
    type: "mysql",
    host: "localhost",
    port: 3306,
    username: "root",
    password: "admin",
    database: "test",
    entities: [
        ...
    ],
    synchronize: true,
    logging: false
}).then(connection => {
    // here you can start to work with your entities
}).catch(error => console.log(error));
```

3) please before creating an issue and waste other's time, make the effort of really understanding whether there is a problem really or not

**Comment by Paul75** [comment]
I am not stupid !

Of course I configure like you wrote !

And same error. ....
