### ISSUE TITLE
[Question] repository

### ISSUE THREAD

**Issue by Paul75** [javieraviles/node-typescript-koa-rest#64]
Hello,

In your structure that can create specific repository in directory repository(for exemple) adn for exemple do a finction like : 

```
@EntityRepository(Evaluation)
export class EvaluationRepository extends Repository<Evaluation> {
    public getListDatesEvaluation(
        beneficiaireId: number
    ): Promise<Evaluation[] | undefined> {
        return this.createQueryBuilder('evaluation')
            .select()
            .leftJoinAndSelect('evaluation.usagers', 'usagers')
            .where('usagers.id IN (:beneficiaireId)', {
                beneficiaireId,
            })
            .orderBy('evaluation.dateEvaluation', 'DESC')
            .getMany();
    }
}
```

Thanks

**Comment by javieraviles** [comment]
Hi!

Do you mean whether it would be possible to do this from the repository? which file exactly do you mean?

**Comment by Paul75** [comment]
Hello,

I mean to create a file name EvaluationRepository and in this add fonctions and call the repository in controller or another service ...

Thanks

**Comment by javieraviles** [comment]
yes sure why not, sounds good
