### ISSUE TITLE
.prettier. configuration is gone

### ISSUE THREAD

**Issue by daywednes** [javieraviles/node-typescript-koa-rest#66]
i saw a PR to add .prettier configuration - why is it gone?

**Comment by javieraviles** [comment]
Hi there,

As you can read in the thread of [PR 54](https://github.com/javieraviles/node-typescript-koa-rest/pull/54), after migrating from TSlint to ESlint, it was already covering formatting good enough, so prettier was not adding much value on top of it. I tried to integrate it too but felt kind of useless.

Javi

**Comment by daywednes** [comment]
Thanks @javieraviles. Let me close this
