### ISSUE TITLE
 a lot of dependency is outdated  can this project be updated

### ISSUE THREAD

**Issue by 2227068304** [javieraviles/node-typescript-koa-rest#69]
this project works really well    but a lot of dependency is outdated Can you update it

**Comment by javieraviles** [comment]
Every once in a while I update dependencies, and so I will soon when I get some free time. But I would also appreciate a PR of course :D

**Comment by javieraviles** [comment]
Hey all dependencies are up to date with latest versions in the new [release 1.8.0](https://github.com/javieraviles/node-typescript-koa-rest/releases/tag/1.8.0) :)
