### ISSUE TITLE
PG version problem

### ISSUE THREAD

**Issue by marindrewliquid** [javieraviles/node-typescript-koa-rest#72]
Hi, I ran into a problem described here with clean repo code:
https://stackoverflow.com/questions/62119498/typeorm-createconnection-return-pending-even-with-await-on-macos-with-pg

After an update of pg

```
npm uninstall pg --save
npm install pg --save
```

the problem went away. Let me know if you want me to create a PR

**Comment by javieraviles** [comment]
Sure it would be more than welcome if you could create a PR upgrading the dependency and check it works fine in both MAC and the CI :)

**Comment by javieraviles** [comment]
Hey in the new [release 1.8.0](https://github.com/javieraviles/node-typescript-koa-rest/releases/tag/1.8.0) I upgraded the pg version so this should not be an issue anymore :)
