### ISSUE TITLE
listener callback should be used

### ISSUE THREAD

**Issue by timhuff** [javieraviles/node-typescript-koa-rest#77]
https://github.com/javieraviles/node-typescript-koa-rest/blob/628b82f5bd4eb09cd9a34c308c7116d745d1c741/src/server.ts#L62

Nitpick but...

This code should be something like:

```ts
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`)
})
```

the last parameter of `listen` is a callback for when the server is listening.

**Comment by javieraviles** [comment]
Thanks! merging a PR including your recommendation, small details are important =)
