### ISSUE TITLE
Swagger is blocked by CSP

### ISSUE THREAD

**Issue by oryxfea** [javieraviles/node-typescript-koa-rest#78]
When I visit `http://localhost:3000/swagger-html`, I got below error in the console.

```
Refused to load the script 'https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/3.21.0/swagger-ui-bundle.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

It turns out that the Content Security Policy enabled by helmet blocks loading swagger related files from CDN, since this issue is gone after comment out `app.use(helmet())`.

**Comment by javieraviles** [comment]
Yes and I can see that happening in the Heroku deployment from the CI as well (https://node-typescript-koa-rest.herokuapp.com/swagger-html). Nice catch, let me explore solutions :)

**Comment by javieraviles** [comment]
[this article](https://www.veracode.com/blog/secure-development/fasten-your-helmetjs-part-2-locking-down-your-content-security-policy) on how to custom CSP for helmet seems interesting

**Comment by javieraviles** [comment]
`app.use(helmet.contentSecurityPolicy({
        directives:{
          defaultSrc:["'self'"],
          scriptSrc:["'self'",'cdnjs.cloudflare.com'],
          styleSrc:["'self'",'cdnjs.cloudflare.com', 'fonts.googleapis.com'],
          fontSrc:["'self'",'fonts.gstatic.com']}}));
`

this would actually make it, but then the inline styles and scripts would get rejected, and adding 'unsafe-inline' as part of the CSP does not seem to be a good idea...

**Comment by javieraviles** [comment]
Looking perfect now with this solution, thanks again for catching it!
